server:
  port: 8800
  shutdown: graceful #graceful:开启优雅停机，默认IMMEDIATE是立即关机

spring:
  application:
    name: pilates-system
  cloud:
    nacos:
      username: ${nacos.username}
      password: ${nacos.password}
      # 配置中心
      config:
        server-addr: ${nacos.server-addr}
        namespace: ${nacos.namespace}
        file-extension: yaml
  config:
    import:
      - nacos:pilates-common.yaml?group=DEFAULT_GROUP&refreshEnabled=true
      - nacos:pilates-system.yaml?group=DEFAULT_GROUP&refreshEnabled=true

dubbo:
  application:
    qos-enable: false
    metadata-type: remote
    shutwait: 16000 # 停止服务等待时间，单位：毫秒
  protocol:
    name: dubbo
    # dubbo 协议端口（ -1 表示自增端口，从 20880 开始）
    port: -1
  scan:
    base-packages: com.jrmall.pilates.system.provider  #dubbo中包扫描
  registry:
    address: nacos://${nacos.server-addr}
    username: ${nacos.username}
    password: ${nacos.password}
    # Dubbo3 默认采用 “应用级服务发现 + 接口级服务发现” 的双注册模式，因此会发现应用级服务（应用名）和接口级服务（接口名）同时出现在 Nacos 控制台，可以通过配置 dubbo.registry.register-mode=instance/interface/all 来改变注册行为。
    register-mode: instance
    parameters:
      namespace: dubbo-dev
  metadata-report:
    address: nacos://${nacos.server-addr}
    username: ${nacos.username}
    password: ${nacos.password}
    parameters:
      namespace: dubbo-metadata-dev
  provider:
#    filter: providerRpcFilter,dubboExceptionFilter,-exception
    timeout: 10000

nacos:
  username: nacos
  password: nacos
  server-addr: http://localhost:8848
  namespace: pilates-cloud-dev


