server:
  port: 9000
  shutdown: graceful #graceful:开启优雅停机，默认IMMEDIATE是立即关机

spring:
  application:
    name: pilates-auth
  cloud:
    nacos:
      username: ${nacos.username}
      password: ${nacos.password}
      # 注册中心
      discovery:
        server-addr: ${nacos.server-addr}
        namespace: ${nacos.spring-cloud.discovery.namespace}
      # 配置中心
      config:
        server-addr: ${nacos.server-addr}
        namespace: ${nacos.spring-cloud.config.namespace}
  config:
    import:
      - nacos:mysql-auth-config.yml?group=DEFAULT_GROUP
      - nacos:redis-config.yml?group=DEFAULT_GROUP
      - nacos:aliyun-sms.yml?group=DEFAULT_GROUP
      - nacos:swagger-config.yml?group=DEFAULT_GROUP
      - nacos:dubbo-consumer.yml?group=DEFAULT_GROUP
      - nacos:pilates-common.yaml?group=DEFAULT_GROUP&refreshEnabled=true
      - nacos:pilates-auth.yaml?group=DEFAULT_GROUP&refreshEnabled=true

nacos:
  username: nacos
  password: nacos
  server-addr: localhost:8848
  spring-cloud:
    config:
      namespace: pilates-cloud-dev
    discovery:
      namespace: springcloud-dev
  dubbo:
    namespace: dubbo-dev
    namespace-metadata: dubbo-metadata-dev

  # 自定义认证配置
custom:
  security:
    # 登录页面路径
    login-url: http://127.0.0.1:9527/oauthlogin
    # 授权确认页面路径
    consent-page-uri: http://127.0.0.1:9527/consent
    # 设备码验证页面
    device-activate-uri: http://127.0.0.1:9527/activate
    # 设备码验证成功页面
    device-activated-uri: http://127.0.0.1:9527/activated
    # 当前认证服务访问的路径
    issuer-url: http://127.0.0.1:9000
    whitelist-paths:
      - /api/v1/auth/captcha
      - /api/v1/auth/sms_code
      - assets/**
      - /webjars/**
      - /login
      - /error
      - /oauth2/consent/parameters
      - /favicon.ico

