server:
  port: 8800
  shutdown: graceful #graceful:开启优雅停机，默认IMMEDIATE是立即关机

spring:
  application:
    name: pilates-system
  cloud:
    nacos:
      username: ${nacos.username}
      password: ${nacos.password}
      # 配置中心
      config:
        server-addr: ${nacos.server-addr}
        namespace: ${nacos.namespace}
        file-extension: yaml
  config:
    import:
      - nacos:pilates-common.yaml?group=DEFAULT_GROUP&refreshEnabled=true
      - nacos:pilates-system.yaml?group=DEFAULT_GROUP&refreshEnabled=true

dubbo:
  application:
    qos-enable: false
    metadata-type: remote
    shutwait: 16000 # 停止服务等待时间，单位：毫秒
  protocol:
    name: dubbo
    # dubbo 协议端口（ -1 表示自增端口，从 20880 开始）
    port: -1
  scan:
    base-packages: com.jrmall.pilates.system.controller  #dubbo中包扫描
  registry:
    address: nacos://${nacos.server-addr}
    username: ${nacos.username}
    password: ${nacos.password}
    register-mode: instance
    parameters:
      namespace: dubbo-dev
      #Dubbo3.0.0版本以后，增加了是否注册消费者的参数，如果需要将消费者注册到nacos注册中心上，需要将参数(register-consumer-url)设置为true，默认是false。
      #register-consumer-url: true
  metadata-report:
    address: nacos://${nacos.server-addr}
    username: ${nacos.username}
    password: ${nacos.password}
    parameters:
      namespace: dubbo-metadata-dev
  consumer:
#    filter: consumerRpcFilter
    timeout: 10000
    retries: 0


nacos:
  username: nacos
  password: nacos
  server-addr: http://localhost:8848
  namespace: pilates-cloud-dev


