server:
  port: 8081
  shutdown: graceful #graceful:开启优雅停机，默认IMMEDIATE是立即关机

spring:
  application:
    name: xxl-job-executor-common
  cloud:
    nacos:
      username: ${nacos.username}
      password: ${nacos.password}
      # 配置中心
      config:
        server-addr: ${nacos.server-addr}
        namespace: ${nacos.spring-cloud.config.namespace}
  config:
    import:
      - nacos:dubbo-consumer-nofilter.yml?group=DEFAULT_GROUP
      - nacos:xxl-job-executor.yaml?group=DEFAULT_GROUP&refreshEnabled=true

nacos:
  username: nacos
  password: nacos
  server-addr: 172.16.85.108:8848
  spring-cloud:
    config:
      namespace: jrmall-cloud-dev

# log config
logging:
  config: classpath:logback.xml
